add css.js to challenges
codicocodes/speedtyper-community pull request #6
Opened 2021-05-18 19:21 UTC by severalpens

Grid CSS sample from MDN Web Docs.

2021-05-19 21:14 UTC, codicocodes requested changes

2021-05-19 21:14 UTC, codicocodes commented on challenges/css.js
> +    license: "CC-BY-SA-2.5",
As the code snippets were added 8 months ago, they seem to be in the public domain: CC0

Any code snippets added on or after August 2020 are in the public domain.

Feel free to fix, otherwise ill fix when merging.

2021-05-19 22:59 UTC, severalpens commented on challenges/css.js
> +    license: "CC-BY-SA-2.5",
Hi Codicocodes, I removed the license and updated the projectUrl to the actual MDN page. All good practise contributing public PRs so feel free to make more change requests if requred or alter directly if required.

2021-05-22 22:53 UTC, closed without merging

2021-05-22 22:55 UTC, severalpens commented
I'll close this PR and replace it with a less messy one.